### PR TITLE
update Dockerfile to latest fluentbit, otel-collector and golang image

### PR DESCRIPTION
**Pull request by a-thaler**
**Description**

Changes proposed in this pull request:

- updated fluentbit to be streamlined with related helm chart in kyma
- updated to latest golang image
- updated otel-collector to 0.71.0

**Related issue(s)**

https://github.com/kyma-project/third-party-images/pull/312

### CODE REVIEW

**Comment by skhalash** [comment]
Let us try Dependabot to bump the versions https://github.com/kyma-project/telemetry-manager/pull/7

**Review by rakesh-garimella — APPROVED** [review]

**Review by rakesh-garimella — APPROVED** [review]

**Pull request merged**
