### PR TITLE
chore: Use the new module-config-file flag when creating module

### PR DESCRIPTION
**Pull request by shorim**
## Description

Changes proposed in this pull request:

- Use the new `module-config-file` flag when creating a module in both `release.sh` and `deploy-module.sh` scripts.
- Update the release artefacts:
   - Add the Telemetry default CR: `telemetry-default-cr.yaml`. This is needed for the module submission pipeline: https://github.tools.sap/kyma/module-manifests
   -  Rename `template.yaml` to `moduletemplate.yaml` and `rendered.yaml` to `telemetry-manager.yaml` to be consistent with the release artefacts from other modules: https://github.com/kyma-project/keda-manager/releases/tag/v0.3.0 and https://github.com/kyma-project/serverless-manager/releases/tag/v0.3.2

## Related Issues and Documents

Closes:

Related issues:

## Traceability

- [ ] The PR is linked to a GitHub Issue.
- [ ] New features have a milestone label set.
- [ ] New features have defined acceptance criteria in a corresponding GitHub Issue, and all criteria are satisfied with this PR.
- [ ] The corresponding GitHub Issue has a respective `area` label.
- [ ] The follow-up issues (if any) are linked in the `Related Issues` section.

## Testability

The feature is unit-tested:

- [ ] Yes.
- [x] No, because unit tests are not needed.
- [ ] No, because of ...

The feature is e2e-tested:

- [ ] Yes.
- [x] No, because e2e-tests are not needed.
- [ ] No, because of ...

Tests conducted for the PR:

## Codebase

- [ ] My code follows the [Effective Go](https://go.dev/doc/effective_go) style guidelines.
- [ ] The code was planned and designed following the defined architecture and the separation of concerns.
- [ ] The code has sufficient comments, particularly for all hard-to-understand areas.
- [ ] This PR adds value and shows no feature creep.
- [ ] I have augmented the test suite that proves my fix is effective or that my feature works.
- [x] Adjusted the documentation if the change is user-facing.

### CODE REVIEW

**Comment by shorim** [comment]
the `pull-telemetry-manager-verify-module` job is failing because of this [issue](https://github.com/kyma-project/cli/issues/1723)

**Review by NHingerl — DISMISSED** [review]

**Review by NHingerl — APPROVED** [review]

**Review by skhalash — APPROVED** [review]

**Pull request merged**
