### PR TITLE
docs: Fix error in self monitor + adjust diagrams

### PR DESCRIPTION
**Pull request by NHingerl**
## Description

Changes proposed in this pull request (what was done and why):

- found + fixed a typo
- adjusted arch diagrams

Changes refer to particular issues, PRs or documents:

- 

## Traceability
- [ ] The PR is linked to a GitHub issue.
- [ ] New features have a milestone set.
- [ ] New features have defined acceptance criteria in a corresponding GitHub Issue, and all criteria are satisfied with this PR.
- [ ] The corresponding GitHub issue has a respective `area` and `kind` label.
- [ ] The follow-up issues (if any) are linked in the `Related Issues` section.
- [ ] Adjusted the documentation if the change is user-facing.
- [ ] The feature is unit-tested
- [ ] The feature is e2e-tested

### CODE REVIEW

**Review by a-thaler — APPROVED** [review]
Nice improvement, thanks a lot. I was thinking if we even could use the same layout it in the domain diagrams as we used for the overview diagram? So letting the data flow always from left to right only, using the same category boxes (instrumentation/collection/storage).
But then can be done in a separate PR

**Comment by NHingerl** [comment]
> Nice improvement, thanks a lot. I was thinking if we even could use the same layout it in the domain diagrams as we used for the overview diagram? So letting the data flow always from left to right only, using the same category boxes (instrumentation/collection/storage). But then can be done in a separate PR

That would be a great next step! For now, I'd use the current diagrams, and we can create a separate task to align the diagrams. More consistency is always good

**Review by mmitoraj — APPROVED** [review]

**Review by mmitoraj — APPROVED** [review]
That is a better user experience indeed!

**Comment by NHingerl** [comment]
adjusted the Help Portal docs accordingly; internal Draft should be updated after the next build.

**Pull request merged**
