### PR TITLE
Remove sleep statement from webhook test

### PR DESCRIPTION
**Pull request by chrkl**
**Description**

Sleep statement increases the test runtime significantly and does not have an obvious use.

Changes proposed in this pull request:

- Remove sleep statement from webhook test

**Related issue(s)**

### CODE REVIEW

**Review by skhalash — APPROVED** [review]

**Comment by chrkl** [comment]
@skhalash would like to run the unit tests on Prow a few times and ensure that it is not introducing any flakiness before merging.

**Pull request merged**
