### PR TITLE
chore: Revert kustomization.yaml and provision-k3d.sh

### PR DESCRIPTION
**Pull request by TeodorSAP**
## Description

Changes proposed in this pull request (what was done and why):

- Revert mistakenly merged changes to kustomization.yaml and provision-k3d.sh

Changes refer to particular issues, PRs or documents:

- Introduced in https://github.com/kyma-project/telemetry-manager/pull/1288

## Traceability
- [ ] The PR is linked to a GitHub issue.
- [ ] The follow-up issues (if any) are linked in the `Related Issues` section.
- [ ] If the change is user-facing, the documentation has been adjusted.
- [ ] The feature is unit-tested.
- [ ] The feature is e2e-tested.

### CODE REVIEW

**Review by k15r — APPROVED** [review]

**Comment by k15r** [comment]
sorry :)

**Comment by skhalash** [comment]
Can you add a check to make sure it never happens again?

**Comment by TeodorSAP** [comment]
> sorry :)

My fault, I should've been more careful during review

**Comment by TeodorSAP** [comment]
> Can you add a check to make sure it never happens again?

For the customization file, you mean?

**Comment by skhalash** [comment]
Yeah, either a pre-commit hook or a GHA workflow step. I also often unintentionally commit it. @k15r What do you think?

**Comment by TeodorSAP** [comment]
> Yeah, either a pre-commit hook or a GHA workflow step. I also often unintentionally commit it. @k15r What do you think?

But what if we want to modify it in the future? Should the check also include some kind of "backdoor"?

**Comment by skhalash** [comment]
Then we can disable the check, look at the git history, we don't change it often

**Pull request merged**
