### PR TITLE
feat: Introduce crd categories

### PR DESCRIPTION
**Pull request by k15r**
## Description

Changes proposed in this pull request (what was done and why):

- group Pipelines into their own category "telemetry"

Changes refer to particular issues, PRs or documents:

- 

## Traceability
- [ ] The PR is linked to a GitHub issue.
- [ ] New features have a milestone set.
- [ ] New features have defined acceptance criteria in a corresponding GitHub Issue, and all criteria are satisfied with this PR.
- [ ] The corresponding GitHub issue has a respective `area` and `kind` label.
- [ ] The follow-up issues (if any) are linked in the `Related Issues` section.
- [ ] Adjusted the documentation if the change is user-facing.
- [ ] The feature is unit-tested
- [ ] The feature is e2e-tested

### CODE REVIEW

**Review by skhalash — APPROVED** [review]

**Comment by skhalash** [comment]
Looks good! Do we have an agreement with other teams to use the kyma-modules category for module CRs?

**Comment by k15r** [comment]
> Looks good! Do we have an agreement with other teams to use the kyma-modules category for module CRs?

nope, not yet. I assume the correct way to introduce it would be a proposal.

**Comment by a-thaler** [comment]
Let's wait for the next release (tuesday) till we merge it

**Review by skhalash — APPROVED** [review]

**Pull request merged**
